### ISSUE TITLE
"Isle has already been configured" error in integration tests

### ISSUE THREAD

**Issue by cremor** [fedarovich/isle#3]
ISLE breaks ASP.NET Core integration tests that are created with `WebApplicationFactory<TEntryPoint>` as documented [here](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0#basic-tests-with-the-default-webapplicationfactory).
With such tests the startup code, and therefore also `IsleConfiguration.Configure()`, is executed once for each test. But ISLE throws an exception on every call after the first one.

**Comment by fedarovich** [comment]
I will make the method `IsleConfiguration.Reset()` public in the next release, so that it can be used in custom unit tests.

As a temporary workaround you can call it with reflection.

**Comment by fedarovich** [comment]
Fixed in 1.3
